### ISSUE TITLE
Only greeting

### ISSUE THREAD

**Issue by petersirka** [raythree/totaljs-mongoose-starter#1]
Hi Bill,
really nice and good luck. Let me know if you have any questions :-)
BTW: your email bill@ip... doesn't work or is wrong.

__Thank you and I appreciate it!__

**Comment by raythree** [comment]
Hi Peter, thanks. My first impression was that it would be hard, and your comment said it would be for the first 2 months. But after a few days I was totally productive. Everything works exactly as you think it should, amazing. I'm a total advocate 😀  Not sure what happened with the email, it's bill@raythree.com

Cheers,
Bill
